### ISSUE TITLE
[iROD-Chat:14505] Re: deploying irods-rest

### ISSUE THREAD

**Issue by michael-conway** [DICE-UNC/irods-rest#29]
I'm working on a Docker container to deploy irods with the rest API to make it easier to run stuff against Travis.
To do this, I figured it would be simple to build irods-rest ( mvn package ) and deploy it to Jetty, but I keep getting this error:

javax.servlet.UnavailableException: org.jboss.resteasy.jsapi.JSAPIServlet
    at org.eclipse.jetty.servlet.BaseHolder.doStart(BaseHolder.java:102)
    at org.eclipse.jetty.servlet.ServletHolder.doStart(ServletHolder.java:338)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
    ....

**Comment by michael-conway** [comment]
..adding jsapi jar to pom.xml
