### ISSUE TITLE
SSL in docker

### ISSUE THREAD

**Issue by matthdsm** [DICE-UNC/irods-rest#61]
Hi,

We're trying to deploy the iRODS rest interface using the new docker image, but are running into some issues regarding the SSL connection.

The image was started using the following command:
```
docker run --rm -p 8080:8080 -v ./irods-rest.properties:/etc/irods-ext/irods-rest.properties -v ./cert/:/tmp/cert diceunc/rest:4.1.10.0-RC1
```

Error Message:
```
Feb 20 08:20:24 pid:24809 remote addresses: 127.0.0.1, 172.17.0.3 ERROR: sslInit: couldn't read certificate chain file. SSL error: error:02001002:system library:fopen:No such file or directory
Feb 20 08:20:24 pid:24809 remote addresses: 127.0.0.1, 172.17.0.3 ERROR: sslInit: couldn't read certificate chain file. SSL error: error:20074002:BIO routines:FILE_CTRL:system lib
Feb 20 08:20:24 pid:24809 remote addresses: 127.0.0.1, 172.17.0.3 ERROR: sslInit: couldn't read certificate chain file. SSL error: error:140DC002:SSL routines:SSL_CTX_use_certificate_chain_file:system lib
Feb 20 08:20:24 pid:24809 remote addresses: 127.0.0.1, 172.17.0.3 ERROR: [-]	/home/irodsbuild/irods/server/core/src/rodsAgent.cpp:594:int runIrodsAgent(sockaddr_un) :  status [SSL_INIT_ERROR]  errno [] -- message []
	[-]	/home/irodsbuild/irods/lib/core/src/sockComm.cpp:132:irods::error sockAgentStart(irods::network_object_ptr) :  status [SSL_INIT_ERROR]  errno [] -- message [failed to call 'agent start']
		[-]	/home/irodsbuild/irods/plugins/network/ssl/libssl.cpp:820:irods::error ssl_agent_start(irods::plugin_context &) :  status [SSL_INIT_ERROR]  errno [] -- message [couldn't initialize SSL context]

Feb 20 08:20:24 pid:571  ERROR: Agent process [24809] exited with status [16]
```
It seems like there's something wrong with the permissions of the keychain.

I was wondering if you could provide any help?

Thanks
M

**Comment by michael-conway** [comment]
Sure, one thing you can do is, with the docker image running...open another
terminal

do a docker ps

look for the generated name for the container, like excited_vole or similar

In that second terminal

docker exec -it exicted_vole_or_whatever_name sh

That opens a shell in the running container, look in the /tmp/cert/
directory, and you should see a server.crt file.  Do you see this?  I bet
it's just naming or something!  Happy to screen share with Google today to
help.

**Comment by matthdsm** [comment]
Hi Michael,

Thanks for the reply. I went and checked, and the `server.crt` file is available.
When starting the server, I got the following message:
```
Cert will be imported
keytool error: java.lang.Exception: Alias <mycert> does not exist
Certificate was added to keystore
running catalina
...
```

Could this have something to do with it?

M

**Comment by matthdsm** [comment]
I did some more digging, and this is the entire warning I get when I curl the rest api

```
2022742 [http-apr-8080-exec-1] INFO  org.irods.jargon.rest.auth.BasicAuthFilter  - BasicAuthFilter.doFilter()
2022769 [http-apr-8080-exec-1] INFO  org.irods.jargon.rest.auth.RestAuthUtils  - getIRODSAccountFromBasicAuthValues
2022770 [http-apr-8080-exec-1] INFO  org.irods.jargon.rest.auth.RestAuthUtils  - index of end of basic prefix:5
2022781 [http-apr-8080-exec-1] INFO  org.irods.jargon.rest.auth.RestAuthUtils  - index of end of basic prefix:5
2022781 [http-apr-8080-exec-1] INFO  org.irods.jargon.rest.auth.RestAuthUtils  - credentials:rods
2022782 [http-apr-8080-exec-1] INFO  org.irods.jargon.rest.auth.RestAuthUtils  - restConfiguration:RestConfiguration [irodsHost=172.17.0.2, irodsPort=1247, irodsZone=tempZone, defaultStorageResource=, realm=irods-rest, utilizePackingStreams=true, authType=STANDARD, allowCors=true, corsOrigins=[*], corsMethods=[GET, POST, DELETE, PUT], corsAllowCredentials=true, corsAllowedHeaders=[x-requested-with, x-requested-by], webInterfaceURL=, sslNegotiationPolicy=CS_NEG_DONT_CARE, computeChecksum=true]
2022782 [http-apr-8080-exec-1] INFO  org.irods.jargon.rest.auth.RestAuthUtils  - using standard auth
2022783 [http-apr-8080-exec-1] INFO  org.irods.jargon.rest.auth.RestAuthUtils  - see if auth scheme is overrideen by the provided credentials
2022784 [http-apr-8080-exec-1] DEBUG org.irods.jargon.rest.auth.RestAuthUtils  - userId:rods
2022786 [http-apr-8080-exec-1] INFO  org.irods.jargon.rest.auth.BasicAuthFilter  - defaut storage resource in irods account:
2022786 [http-apr-8080-exec-1] INFO  org.irods.jargon.rest.auth.BasicAuthFilter  - irods account for auth:irods://rods@172.17.0.2:1247
2022787 [http-apr-8080-exec-1] INFO  org.irods.jargon.core.pub.IRODSAccessObjectFactoryImpl  - authenticateIRODSAccount()
2022787 [http-apr-8080-exec-1] INFO  org.irods.jargon.core.pub.IRODSAccessObjectFactoryImpl  - any existing session will be closed, or at least handed back to a pool/cache
2022788 [http-apr-8080-exec-1] WARN  org.irods.jargon.core.connection.IRODSSession  - closing session that is already closed, silently ignore
2022795 [http-apr-8080-exec-1] INFO  org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocolFactory  - instance() method...calling connection life cycle
2022796 [http-apr-8080-exec-1] INFO  org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocolFactory  - create connection....
2022796 [http-apr-8080-exec-1] INFO  org.irods.jargon.core.connection.IRODSTCPConnectionFactoryImpl  - instance()
2022799 [http-apr-8080-exec-1] INFO  org.irods.jargon.core.connection.AbstractConnection  - AbstractConnection()
2022800 [http-apr-8080-exec-1] INFO  org.irods.jargon.core.connection.AbstractConnection  - using default negotiation policy:ClientServerNegotiationPolicy [sslNegotiationPolicy=CS_NEG_DONT_CARE]
2022800 [http-apr-8080-exec-1] INFO  org.irods.jargon.core.connection.AbstractConnection  - opening irods socket
2022814 [http-apr-8080-exec-1] INFO  org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocolFactory  - ...have connection, now authenticate given the auth scheme in the iRODS account...
2022814 [http-apr-8080-exec-1] INFO  org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocolFactory  - authenticate()
2022814 [http-apr-8080-exec-1] INFO  org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocolFactory  - get auth mechanism
2022814 [http-apr-8080-exec-1] INFO  org.irods.jargon.core.connection.AuthenticationFactoryImpl  - instanceAuthMechanism()
2022815 [http-apr-8080-exec-1] INFO  org.irods.jargon.core.connection.AuthenticationFactoryImpl  - authScheme:STANDARD
2022815 [http-apr-8080-exec-1] INFO  org.irods.jargon.core.connection.AuthenticationFactoryImpl  - using standard auth
2022817 [http-apr-8080-exec-1] INFO  org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocolFactory  - authenticate...
2022817 [http-apr-8080-exec-1] INFO  org.irods.jargon.core.connection.AuthMechanism  - sendStartupPacket()
2022824 [http-apr-8080-exec-1] INFO  org.irods.jargon.core.connection.AuthMechanism  - clientServerNegotiationHook()
2022824 [http-apr-8080-exec-1] INFO  org.irods.jargon.core.connection.AuthMechanism  - negotiation is required
2022824 [http-apr-8080-exec-1] INFO  org.irods.jargon.core.connection.AuthMechanism  - clientServerNegotiation()
2022880 [http-apr-8080-exec-1] INFO  org.irods.jargon.core.connection.AuthMechanism  - have a server negotiation response:ClientServerNegotiationStruct [status=1, sslNegotiationPolicy=CS_NEG_DONT_CARE]
2022889 [http-apr-8080-exec-1] INFO  org.irods.jargon.core.connection.ClientServerNegotiationService  - negotiate()
2022889 [http-apr-8080-exec-1] INFO  org.irods.jargon.core.connection.ClientServerNegotiationService  - negotiateUsingServerProtocol()
2022889 [http-apr-8080-exec-1] INFO  org.irods.jargon.core.connection.ClientServerNegotiationService  - negotiation over response from server:ClientServerNegotiationStruct [status=1, sslNegotiationPolicy=CS_NEG_DONT_CARE]
2022889 [http-apr-8080-exec-1] INFO  org.irods.jargon.core.connection.ClientServerNegotiationService  - client policy:ClientServerNegotiationPolicy [sslNegotiationPolicy=CS_NEG_DONT_CARE]
2022890 [http-apr-8080-exec-1] INFO  org.irods.jargon.core.connection.ClientServerNegotiationService  - negotiatedOutcome:CS_NEG_USE_SSL
2022890 [http-apr-8080-exec-1] INFO  org.irods.jargon.core.connection.ClientServerNegotiationService  - was a success, return choice to server
2022902 [http-apr-8080-exec-1] INFO  org.irods.jargon.core.connection.ClientServerNegotiationService  - startupResponse captured:StartupResponseData:
   status:0
   relVersion:rods4.2.0
   apiVersion:d
   reconnPort:0
   reconnAddr:
   cookie:400
2022902 [http-apr-8080-exec-1] INFO  org.irods.jargon.core.connection.ClientServerNegotiationService  - wrapConnectionInSsl()
2022903 [http-apr-8080-exec-1] INFO  org.irods.jargon.core.connection.ClientServerNegotiationService  - wrapping in ssl connection
2022904 [http-apr-8080-exec-1] INFO  org.irods.jargon.core.connection.SslConnectionUtilities  - createSslSocketForProtocolAndIntegrateIntoProtocol()
2023133 [http-apr-8080-exec-1] ERROR org.irods.jargon.core.connection.SslConnectionUtilities  - ssl exception in handshake
javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:992)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
	at org.irods.jargon.core.connection.SslConnectionUtilities.createSslSocketForProtocol(SslConnectionUtilities.java:166)
	at org.irods.jargon.core.connection.SslConnectionUtilities.createSslSocketForProtocolAndIntegrateIntoProtocol(SslConnectionUtilities.java:200)
	at org.irods.jargon.core.connection.ClientServerNegotiationService.wrapConnectionInSslIfConfigured(ClientServerNegotiationService.java:210)
	at org.irods.jargon.core.connection.ClientServerNegotiationService.notifyServerOfNegotiationSuccess(ClientServerNegotiationService.java:182)
	at org.irods.jargon.core.connection.ClientServerNegotiationService.negotiateUsingServerProtocol(ClientServerNegotiationService.java:142)
	at org.irods.jargon.core.connection.ClientServerNegotiationService.negotiate(ClientServerNegotiationService.java:111)
	at org.irods.jargon.core.connection.AuthMechanism.clientServerNegotiation(AuthMechanism.java:174)
	at org.irods.jargon.core.connection.AuthMechanism.clientServerNegotiationHook(AuthMechanism.java:78)
	at org.irods.jargon.core.connection.AuthMechanism.authenticate(AuthMechanism.java:214)
	at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocolFactory.authenticate(AbstractIRODSMidLevelProtocolFactory.java:241)
	at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocolFactory.instance(AbstractIRODSMidLevelProtocolFactory.java:103)
	at org.irods.jargon.core.connection.IRODSProtocolManager.createNewProtocol(IRODSProtocolManager.java:146)
	at org.irods.jargon.core.connection.IRODSSimpleProtocolManager.getIRODSProtocol(IRODSSimpleProtocolManager.java:69)
	at org.irods.jargon.core.connection.IRODSSession.connectAndAddToProtocolsMap(IRODSSession.java:511)
	at org.irods.jargon.core.connection.IRODSSession.currentConnection(IRODSSession.java:400)
	at org.irods.jargon.core.pub.IRODSAccessObjectFactoryImpl.authenticateIRODSAccount(IRODSAccessObjectFactoryImpl.java:81)
	at org.irods.jargon.rest.auth.BasicAuthFilter.doFilter(BasicAuthFilter.java:130)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:259)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:509)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1104)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:684)
	at org.apache.tomcat.util.net.AprEndpoint$SocketWithOptionsProcessor.run(AprEndpoint.java:2445)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.EOFException: SSL peer shut down incorrectly
	at sun.security.ssl.InputRecord.read(InputRecord.java:505)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
	... 42 more
2023140 [http-apr-8080-exec-1] WARN  org.irods.jargon.rest.auth.BasicAuthFilter  - auth exception
org.irods.jargon.core.exception.JargonException: unable to start SSL socket
	at org.irods.jargon.core.connection.SslConnectionUtilities.createSslSocketForProtocol(SslConnectionUtilities.java:169)
	at org.irods.jargon.core.connection.SslConnectionUtilities.createSslSocketForProtocolAndIntegrateIntoProtocol(SslConnectionUtilities.java:200)
	at org.irods.jargon.core.connection.ClientServerNegotiationService.wrapConnectionInSslIfConfigured(ClientServerNegotiationService.java:210)
	at org.irods.jargon.core.connection.ClientServerNegotiationService.notifyServerOfNegotiationSuccess(ClientServerNegotiationService.java:182)
	at org.irods.jargon.core.connection.ClientServerNegotiationService.negotiateUsingServerProtocol(ClientServerNegotiationService.java:142)
	at org.irods.jargon.core.connection.ClientServerNegotiationService.negotiate(ClientServerNegotiationService.java:111)
	at org.irods.jargon.core.connection.AuthMechanism.clientServerNegotiation(AuthMechanism.java:174)
	at org.irods.jargon.core.connection.AuthMechanism.clientServerNegotiationHook(AuthMechanism.java:78)
	at org.irods.jargon.core.connection.AuthMechanism.authenticate(AuthMechanism.java:214)
	at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocolFactory.authenticate(AbstractIRODSMidLevelProtocolFactory.java:241)
	at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocolFactory.instance(AbstractIRODSMidLevelProtocolFactory.java:103)
	at org.irods.jargon.core.connection.IRODSProtocolManager.createNewProtocol(IRODSProtocolManager.java:146)
	at org.irods.jargon.core.connection.IRODSSimpleProtocolManager.getIRODSProtocol(IRODSSimpleProtocolManager.java:69)
	at org.irods.jargon.core.connection.IRODSSession.connectAndAddToProtocolsMap(IRODSSession.java:511)
	at org.irods.jargon.core.connection.IRODSSession.currentConnection(IRODSSession.java:400)
	at org.irods.jargon.core.pub.IRODSAccessObjectFactoryImpl.authenticateIRODSAccount(IRODSAccessObjectFactoryImpl.java:81)
	at org.irods.jargon.rest.auth.BasicAuthFilter.doFilter(BasicAuthFilter.java:130)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:259)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:509)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1104)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:684)
	at org.apache.tomcat.util.net.AprEndpoint$SocketWithOptionsProcessor.run(AprEndpoint.java:2445)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:992)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
	at org.irods.jargon.core.connection.SslConnectionUtilities.createSslSocketForProtocol(SslConnectionUtilities.java:166)
	... 38 more
Caused by: java.io.EOFException: SSL peer shut down incorrectly
	at sun.security.ssl.InputRecord.read(InputRecord.java:505)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
	... 42 more
2023141 [http-apr-8080-exec-1] WARN  org.irods.jargon.core.connection.IRODSSession  - closing session that is already closed, silently ignore
```

I used the following command:
```
curl -i http://rods:rodspswd@172.17.0.3:8080/irods-rest/rest/collection/tempZone/home/rods/index.html
```

I can see the request coming in, using the correct credentials, but the SSL handshake seems to fail. Could there be something that needs to be configured on the iRODS server?

M

**Comment by michael-conway** [comment]
That almost looks like a misconfiguration on the iRODS side.  Can you use
icommands when your client irods_environment.json designates a policy that
will use SSL?  Like CS_NEG_DONT_CARE...

**Comment by matthdsm** [comment]
You're absolutely right. I've changed the ssl param to NO_NEGOTIATION, and everything works fine now. Currently we don't need much security, since we're just testing, but now we know where to look when we go to production.

Thanks a lot!
M

**Comment by michael-conway** [comment]
Yes, the biggest thing that has tripped people up is that if the client and
server say "I don't care" then iRODS will try to do SSL.
